### ISSUE TITLE
It would be nice to have scheduled closing so that if the door is open after x time it gets closed.

### ISSUE THREAD

**Issue by MarkKropf** [robdimsdale/garagepi#1]
^^

**Comment by robdimsdale** [comment]
It would be nice. Nobody likes to leave their garage door open all night. Currently this would be very hard to implement, as the garage door is a toggle - we don't know what state the garage door is in. So we can't 'close' it.

I think the right way to solve this is to add support for extra hardware to sense the state of the garage door, and then we can choose whether it should be open or closed. I'm very much in favor of this solution. See the associated [story in tracker](https://www.pivotaltracker.com/story/show/101008826) for prioritization.

As always, PR (or hardware shipment!) welcome.
